### ISSUE TITLE
gateway(encoding): support utf-8

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh#98] opened 2022-05-31 10:47 UTC
Very little care is given for properly handling or responding to utf-8 based urls or headers.

**Comment by b5** [comment] 2022-09-29 19:22
can confirm this is a problem. Example: https://cloudflare-ipfs.com/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme renders properly, on iroh, not so much:

<img width="1512" alt="Screen Shot 2022-09-29 at 3 22 20 PM" src="https://user-images.githubusercontent.com/1154390/193123563-9a4dbd70-4df6-4dd2-bd56-d43fd2449ae0.png">

**Comment by fabricedesre** [comment] 2022-09-29 21:00
That's because cloudflare does content-type sniffing and returns `content-type: text/plain; charset=utf-8` while the browser fails to figure out it's utf-8.

That's a dupe of https://github.com/n0-computer/iroh/issues/197

**Closed** 2022-10-14 08:17 UTC
Labels: c-gateway
