### ISSUE TITLE
Another panic in iroh-net

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1286] opened 2023-07-20 15:27 UTC
This one is not in our code but in the default-net crate.

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `5`', /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/default-net-0.16.2/src/gateway/macos.rs:293:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: default_net::gateway::macos::get_default_gateway
   5: default_net::interface::unix::interfaces
   6: iroh_net::net::ip::LocalAddresses::new
   7: iroh_net::magicsock::Actor::determine_endpoints::{{closure}}::{{closure}}
   8: iroh_net::magicsock::Actor::update_endpoints::{{closure}}::{{closure}}
   9: iroh_net::magicsock::Actor::run::{{closure}}
  10: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  12: tokio::runtime::task::core::Core<T,S>::poll
  13: tokio::runtime::task::harness::Harness<T,S>::poll
  14: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  15: tokio::runtime::scheduler::multi_thread::worker::Context::run
  16: tokio::runtime::context::scoped::Scoped<T>::set
  17: tokio::runtime::context::runtime::enter_runtime
  18: tokio::runtime::scheduler::multi_thread::worker::run
  19: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  20: tokio::runtime::task::core::Core<T,S>::poll
  21: tokio::runtime::task::harness::Harness<T,S>::poll
  22: tokio::runtime::blocking::pool::Inner::run
  ```

**Comment by ramfox** [comment] 2023-10-17 18:36
Hey, was this ever addressed or worked out? Any more details, if so?

**Comment by dignifiedquire** [comment] 2023-10-17 18:46
duplicate of https://github.com/n0-computer/iroh/issues/1442

**Closed by dignifiedquire** 2023-10-17 18:46 UTC
Labels: bug, c-iroh-net
