### ISSUE TITLE
iroh doesn't compiles on Android with Neon - `ld: error: duplicate symbol: blake3_compress_in_place_portable`

### ISSUE THREAD

**Issue by Voronar** [n0-computer/iroh#1805] opened 2023-11-13 19:19 UTC
Android build settings:
```gradle
android {
    compileSdk 34
    ndkVersion "25.2.9519653"

    defaultConfig {
        minSdk 24
        targetSdk 33
    }
}
```
iroh: v0.10

Error:
```
ld: error: duplicate symbol: blake3_compress_in_place_portable
          >>> defined at ffi_neon.rs:37 (src/ffi_neon.rs:37)
          >>>            iroh_blake3-1c414b619f1f58b4.iroh_blake3.ac6b13366874c9bc-cgu.0.rcgu.o:(blake3_compress_in_place_portable) in archive
```

But if I disable Neon in my app crate with `iroh-blake3 = { version = "*", features = ["no_neon"]}` it compiles.

**Comment by dignifiedquire** [comment] 2023-11-13 22:54
https://github.com/n0-computer/iroh-blake3/pull/2 should fix this (hopefully)

**Comment by rklaehn** [comment] 2023-11-14 10:42
So the issue is that we had to fork blake3 to get some performance improvements for bao in. But it exports symbols, so if you have the normal blake3 in your dependencies there will be a collision.

One way to solve this would be to directly use our iroh-blake3 instead of blake3 in your other code. But we realize that this is not always possible.

We hope to get these very minor changes upstreamed to blake3 soon.

**Comment by flub** [comment] 2023-11-24 12:53
@link2xt did you see https://github.com/n0-computer/iroh-blake3/pull/2 as the fix to this?

We should merge and depend on that really.

**Comment by rklaehn** [comment] 2023-12-20 08:07
i think this should be solved by the changes in iroh-blake3, and will be solved permanently by the new blake3 guts api that will allow us to directly build on blake3 without fork: https://github.com/BLAKE3-team/BLAKE3/tree/guts_api/rust/guts

**Comment by dignifiedquire** [comment] 2024-02-12 11:02
I believe this is fixed in the latest releases

**Closed by dignifiedquire** 2024-02-12 11:02 UTC
